appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IOh4atTxLu5/ks13CZk2UM9h4v7G6UZqZyPGLpo2jInVRWtvVuso0ScPWmRJ7+Bf7+B4Rf9ngNIFnCUx+5A3vC4BVD82rTijre/yMqXa3N86qPwf0119/3vQW2S8fpV+z+BiykaS10A36LVXYY5Mmz7r5KA545DOXBHVowpJOhqZCtEvl9HFtiCrt3USDHYphNQGCEVQW2QLFT8aWfiyDdeYWatlgCLv0u5q7LC9EnEkuQELWH5bHYqP/yOTQMKL9fWUqTXX7kGFjmyAm6pCzXZPtP0/ubKCHYUy7rvYF14knZDLDW138kHxufMmdnGC7F83X+2DmlW7Z6Dow/dFKGDJDhnP7xtqh8mnGzmp75Xby5bCn7K8xQoJxHgkhaiwjUE+/5NC5tC3C9oomMyPLcz+tENsBvM4DSJmS+SZSq8tfGyQTZ3ffYhRqc7PekejyoTe1u+tYVUkDEfSwaootwJTnTGxZ8C+8tAsCFGazYong2ZcHLfjC2y1pOjzqk7d2PqsXzjKDLClzsrp4Avyni7XtzT1Zlwa8qrd5ZGUC7kc2T4Txpaf0aQZKYvYKNLS+q0IKTGhakrflstixmnlL7r7ZZ4LC9WylOvgmWdtv3fj+B7Bg+SViLZVcZWRrglBi9ZmjW3dPdMreOAxrf1UT57JlD7bWgauGfHlGj1leJE=}
provider:
  win: azure
